import { EpisodeFormData } from '@/lib/types';

export const sampleEpisodes: EpisodeFormData[] = [
  {
    episode_no: 1,
    phase: 'Judges',
    city: 'Karachi',
    week: '1',
    record_start: '2025-09-15T10:00:00+05:00',
    record_end: '2025-09-15T18:00:00+05:00',
    record_venue: 'Karachi Arts Council',
    air_start: '2025-09-20T20:00:00+05:00',
    air_end: '2025-09-20T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 20,
    performances_locked: 15,
    golden_mics_available: 3,
    golden_mics_used: 1,
    voting_enabled: true,
    format_summary: 'Initial auditions with celebrity judges',
    notes: 'First episode of the season. High expectations from audience.',
  },
  {
    episode_no: 2,
    phase: 'Judges',
    city: 'Lahore',
    week: '1',
    record_start: '2025-09-16T10:00:00+05:00',
    record_end: '2025-09-16T18:00:00+05:00',
    record_venue: 'Alhamra Arts Council',
    air_start: '2025-09-21T20:00:00+05:00',
    air_end: '2025-09-21T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 18,
    performances_locked: 18,
    golden_mics_available: 3,
    golden_mics_used: 2,
    voting_enabled: true,
    format_summary: 'Lahore auditions with special guest judge',
    notes: 'All performances locked. Ready for airing.',
  },
  {
    episode_no: 3,
    phase: 'Workshop-Piano',
    city: 'Islamabad',
    week: '2',
    record_start: '2025-09-22T14:00:00+05:00',
    record_end: '2025-09-22T20:00:00+05:00',
    record_venue: 'Pakistan National Council of Arts',
    air_start: '2025-09-27T20:00:00+05:00',
    air_end: '2025-09-27T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 12,
    performances_locked: 8,
    golden_mics_available: 2,
    golden_mics_used: 0,
    voting_enabled: false,
    format_summary: 'Piano workshop with music mentors',
    notes: 'Workshop session. No voting during this phase.',
  },
  {
    episode_no: 4,
    phase: 'Gala',
    city: 'Karachi',
    week: '3',
    record_start: '2025-09-30T19:00:00+05:00',
    record_end: '2025-09-30T23:00:00+05:00',
    record_venue: 'Expo Center Karachi',
    air_start: '2025-10-03T20:00:00+05:00',
    air_end: '2025-10-03T23:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 8,
    performances_locked: 6,
    golden_mics_available: 1,
    golden_mics_used: 1,
    voting_enabled: true,
    format_summary: 'Grand gala night with live audience',
    notes: 'Special gala event. Live voting enabled.',
  },
  {
    episode_no: 5,
    phase: 'Judges',
    city: 'Peshawar',
    week: '2',
    record_start: '2025-10-05T10:00:00+05:00',
    record_end: '2025-10-05T18:00:00+05:00',
    record_venue: 'Nishtar Hall',
    air_start: '2025-10-10T20:00:00+05:00',
    air_end: '2025-10-10T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 15,
    performances_locked: 0,
    golden_mics_available: 3,
    golden_mics_used: 0,
    voting_enabled: true,
    format_summary: 'Peshawar regional auditions',
    notes: 'Planning phase. Recording scheduled for next week.',
  },
  {
    episode_no: 6,
    phase: 'Judges',
    city: 'Quetta',
    week: '3',
    record_start: '2025-02-12T10:00:00+05:00',
    record_end: '2025-02-12T18:00:00+05:00',
    record_venue: 'Quetta Arts Council',
    air_start: '2025-02-17T20:00:00+05:00',
    air_end: '2025-02-17T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 16,
    performances_locked: 12,
    golden_mics_available: 3,
    golden_mics_used: 1,
    voting_enabled: true,
    format_summary: 'Quetta regional auditions',
    notes: 'Balochistan talent showcase.',
  },
  {
    episode_no: 7,
    phase: 'Workshop-Piano',
    city: 'Lahore',
    week: '4',
    record_start: '2025-02-19T14:00:00+05:00',
    record_end: '2025-02-19T20:00:00+05:00',
    record_venue: 'Alhamra Arts Council',
    air_start: '2025-02-24T20:00:00+05:00',
    air_end: '2025-02-24T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 10,
    performances_locked: 7,
    golden_mics_available: 2,
    golden_mics_used: 0,
    voting_enabled: false,
    format_summary: 'Advanced piano techniques workshop',
    notes: 'Second workshop session focusing on advanced techniques.',
  },
  {
    episode_no: 8,
    phase: 'Gala',
    city: 'Lahore',
    week: '5',
    record_start: '2025-02-26T19:00:00+05:00',
    record_end: '2025-02-26T23:00:00+05:00',
    record_venue: 'Expo Center Lahore',
    air_start: '2025-03-03T20:00:00+05:00',
    air_end: '2025-03-03T23:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 6,
    performances_locked: 4,
    golden_mics_available: 1,
    golden_mics_used: 1,
    voting_enabled: true,
    format_summary: 'Lahore gala night with special performances',
    notes: 'Lahore gala event with celebrity guests.',
  },
  {
    episode_no: 9,
    phase: 'Judges',
    city: 'Multan',
    week: '4',
    record_start: '2025-03-05T10:00:00+05:00',
    record_end: '2025-03-05T18:00:00+05:00',
    record_venue: 'Multan Arts Council',
    air_start: '2025-03-10T20:00:00+05:00',
    air_end: '2025-03-10T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 14,
    performances_locked: 0,
    golden_mics_available: 3,
    golden_mics_used: 0,
    voting_enabled: true,
    format_summary: 'Multan regional auditions',
    notes: 'Southern Punjab talent showcase.',
  },
  {
    episode_no: 10,
    phase: 'Judges',
    city: 'Faisalabad',
    week: '5',
    record_start: '2025-09-05T10:00:00+05:00',
    record_end: '2025-09-05T18:00:00+05:00',
    record_venue: 'Faisalabad Arts Council',
    air_start: '2025-09-10T20:00:00+05:00',
    air_end: '2025-09-10T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 17,
    performances_locked: 0,
    golden_mics_available: 3,
    golden_mics_used: 0,
    voting_enabled: true,
    format_summary: 'Faisalabad regional auditions',
    notes: 'Industrial city talent showcase.',
  },
  {
    episode_no: 11,
    phase: 'Judges',
    city: 'Rawalpindi',
    week: '6',
    record_start: '2025-09-08T10:00:00+05:00',
    record_end: '2025-09-08T18:00:00+05:00',
    record_venue: 'Rawalpindi Arts Council',
    air_start: '2025-09-13T20:00:00+05:00',
    air_end: '2025-09-13T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 16,
    performances_locked: 0,
    golden_mics_available: 3,
    golden_mics_used: 0,
    voting_enabled: true,
    format_summary: 'Rawalpindi regional auditions',
    notes: 'Twin city talent showcase.',
  },
  {
    episode_no: 12,
    phase: 'Workshop-Piano',
    city: 'Karachi',
    week: '7',
    record_start: '2025-09-12T14:00:00+05:00',
    record_end: '2025-09-12T20:00:00+05:00',
    record_venue: 'Karachi Arts Council',
    air_start: '2025-09-17T20:00:00+05:00',
    air_end: '2025-09-17T22:00:00+05:00',
    channel: 'ARY Digital',
    performances_planned: 8,
    performances_locked: 0,
    golden_mics_available: 2,
    golden_mics_used: 0,
    voting_enabled: false,
    format_summary: 'Final piano workshop session',
    notes: 'Last workshop before elimination rounds.',
  },
];

export const sampleUsers = [
  {
    email: 'admin@pakistanidol.com',
    name: 'Admin User',
    role: 'Editor' as const,
  },
  {
    email: 'viewer@pakistanidol.com',
    name: 'Viewer User',
    role: 'Viewer' as const,
  },
];

export const sampleContestants = [
  {
    name: 'Ayesha Khan',
    age: 22,
    city: 'Karachi',
    phone: '+92-300-1234567',
    email: 'ayesha.khan@email.com',
    bio: 'Classical singer with 5 years of training. Specializes in ghazals and classical music.',
    audition_date: '2024-12-10T10:00:00+05:00',
    audition_city: 'Karachi',
    audition_venue: 'Karachi Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Hassan Ali',
    age: 25,
    city: 'Lahore',
    phone: '+92-300-2345678',
    email: 'hassan.ali@email.com',
    bio: 'Pop singer and guitarist. Performs contemporary Pakistani and international songs.',
    audition_date: '2024-12-11T14:00:00+05:00',
    audition_city: 'Lahore',
    audition_venue: 'Alhamra Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Fatima Sheikh',
    age: 20,
    city: 'Islamabad',
    phone: '+92-300-3456789',
    email: 'fatima.sheikh@email.com',
    bio: 'Young talent with powerful vocals. Loves to sing Bollywood and Pakistani film songs.',
    audition_date: '2024-12-12T11:00:00+05:00',
    audition_city: 'Islamabad',
    audition_venue: 'Pakistan National Council of Arts',
    status: 'Competing' as const,
  },
  {
    name: 'Ahmed Raza',
    age: 28,
    city: 'Peshawar',
    phone: '+92-300-4567890',
    email: 'ahmed.raza@email.com',
    bio: 'Pashto and Urdu singer. Brings traditional folk music to the competition.',
    audition_date: '2024-12-13T15:00:00+05:00',
    audition_city: 'Peshawar',
    audition_venue: 'Nishtar Hall',
    status: 'Competing' as const,
  },
  {
    name: 'Sara Ahmed',
    age: 24,
    city: 'Karachi',
    phone: '+92-300-5678901',
    email: 'sara.ahmed@email.com',
    bio: 'Jazz and blues singer with a unique voice. Performs both English and Urdu songs.',
    audition_date: '2024-12-14T16:00:00+05:00',
    audition_city: 'Karachi',
    audition_venue: 'Karachi Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Muhammad Usman',
    age: 26,
    city: 'Lahore',
    phone: '+92-300-6789012',
    email: 'muhammad.usman@email.com',
    bio: 'Rock and metal vocalist. Known for high-energy performances and stage presence.',
    audition_date: '2024-12-15T12:00:00+05:00',
    audition_city: 'Lahore',
    audition_venue: 'Alhamra Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Zainab Malik',
    age: 21,
    city: 'Quetta',
    phone: '+92-300-7890123',
    email: 'zainab.malik@email.com',
    bio: 'Balochi folk singer with a melodious voice. Represents Balochistan culture.',
    audition_date: '2024-12-16T13:00:00+05:00',
    audition_city: 'Quetta',
    audition_venue: 'Quetta Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Ali Hassan',
    age: 23,
    city: 'Multan',
    phone: '+92-300-8901234',
    email: 'ali.hassan@email.com',
    bio: 'Sufi and qawwali singer. Brings spiritual music to the competition.',
    audition_date: '2024-12-17T17:00:00+05:00',
    audition_city: 'Multan',
    audition_venue: 'Multan Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Nida Khan',
    age: 19,
    city: 'Faisalabad',
    phone: '+92-300-9012345',
    email: 'nida.khan@email.com',
    bio: 'Youngest contestant with incredible range. Specializes in high-pitched classical songs.',
    audition_date: '2024-12-18T10:00:00+05:00',
    audition_city: 'Faisalabad',
    audition_venue: 'Faisalabad Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Omar Sheikh',
    age: 27,
    city: 'Karachi',
    phone: '+92-300-0123456',
    email: 'omar.sheikh@email.com',
    bio: 'R&B and soul singer. Known for emotional performances and vocal control.',
    audition_date: '2024-12-19T14:00:00+05:00',
    audition_city: 'Karachi',
    audition_venue: 'Karachi Arts Council',
    status: 'Competing' as const,
  },
  {
    name: 'Saima Bibi',
    age: 24,
    city: 'Lahore',
    phone: '+92-300-1111111',
    email: 'saima.bibi@email.com',
    bio: 'Classical singer who struggled with modern songs. Eliminated in early rounds.',
    audition_date: '2024-12-20T10:00:00+05:00',
    audition_city: 'Lahore',
    audition_venue: 'Alhamra Arts Council',
    status: 'Eliminated' as const,
  },
  {
    name: 'Rashid Ahmed',
    age: 30,
    city: 'Peshawar',
    phone: '+92-300-2222222',
    email: 'rashid.ahmed@email.com',
    bio: 'Pashto folk singer with limited Urdu repertoire. Eliminated due to language barrier.',
    audition_date: '2024-12-21T15:00:00+05:00',
    audition_city: 'Peshawar',
    audition_venue: 'Nishtar Hall',
    status: 'Eliminated' as const,
  },
  {
    name: 'Mehwish Khan',
    age: 22,
    city: 'Islamabad',
    phone: '+92-300-3333333',
    email: 'mehwish.khan@email.com',
    bio: 'Young talent with stage fright issues. Eliminated after poor live performance.',
    audition_date: '2024-12-22T11:00:00+05:00',
    audition_city: 'Islamabad',
    audition_venue: 'Pakistan National Council of Arts',
    status: 'Eliminated' as const,
  },
  {
    name: 'Bilal Qureshi',
    age: 26,
    city: 'Karachi',
    phone: '+92-300-4444444',
    email: 'bilal.qureshi@email.com',
    bio: 'Rock singer who was eliminated in the semi-finals. Had great potential.',
    audition_date: '2024-12-23T16:00:00+05:00',
    audition_city: 'Karachi',
    audition_venue: 'Karachi Arts Council',
    status: 'Eliminated' as const,
  },
  {
    name: 'Amina Shah',
    age: 19,
    city: 'Lahore',
    phone: '+92-300-5555555',
    email: 'amina.shah@email.com',
    bio: 'Youngest eliminated contestant. Great voice but lacked experience.',
    audition_date: '2024-12-24T12:00:00+05:00',
    audition_city: 'Lahore',
    audition_venue: 'Alhamra Arts Council',
    status: 'Eliminated' as const,
  },
];

export const sampleContestantEpisodes = [
  // Ayesha Khan performances
  { contestant_name: 'Ayesha Khan', episode_no: 1, performance_order: 3, song_title: 'Aaj Jaane Ki Zid Na Karo', performance_notes: 'Classical ghazal performance with tabla accompaniment' },
  { contestant_name: 'Ayesha Khan', episode_no: 3, performance_order: 1, song_title: 'Lag Ja Gale', performance_notes: 'Piano workshop performance - classical Bollywood song' },
  { contestant_name: 'Ayesha Khan', episode_no: 4, performance_order: 2, song_title: 'Tere Bina Zindagi Se', performance_notes: 'Gala night performance with full orchestra' },
  
  // Hassan Ali performances
  { contestant_name: 'Hassan Ali', episode_no: 1, performance_order: 5, song_title: 'Tum Hi Ho', performance_notes: 'Contemporary pop song with guitar accompaniment' },
  { contestant_name: 'Hassan Ali', episode_no: 2, performance_order: 4, song_title: 'Channa Mereya', performance_notes: 'Modern Bollywood song with acoustic guitar' },
  { contestant_name: 'Hassan Ali', episode_no: 4, performance_order: 6, song_title: 'Perfect', performance_notes: 'Ed Sheeran cover with guitar and harmonica' },
  
  // Fatima Sheikh performances
  { contestant_name: 'Fatima Sheikh', episode_no: 2, performance_order: 2, song_title: 'Ae Watan', performance_notes: 'Patriotic song with emotional delivery' },
  { contestant_name: 'Fatima Sheikh', episode_no: 3, performance_order: 3, song_title: 'Kal Ho Naa Ho', performance_notes: 'Piano workshop - emotional Bollywood ballad' },
  { contestant_name: 'Fatima Sheikh', episode_no: 6, performance_order: 1, song_title: 'Tum Se Hi', performance_notes: 'Jab We Met song with piano accompaniment' },
  
  // Ahmed Raza performances
  { contestant_name: 'Ahmed Raza', episode_no: 2, performance_order: 6, song_title: 'Laila O Laila', performance_notes: 'Pashto folk song with traditional instruments' },
  { contestant_name: 'Ahmed Raza', episode_no: 5, performance_order: 3, song_title: 'Dil Dil Pakistan', performance_notes: 'Patriotic song in Urdu and Pashto' },
  { contestant_name: 'Ahmed Raza', episode_no: 6, performance_order: 4, song_title: 'Kalaam-e-Iqbal', performance_notes: 'Traditional poetry with folk music' },
  
  // Sara Ahmed performances
  { contestant_name: 'Sara Ahmed', episode_no: 3, performance_order: 2, song_title: 'Summertime', performance_notes: 'Jazz standard with piano and saxophone' },
  { contestant_name: 'Sara Ahmed', episode_no: 4, performance_order: 1, song_title: 'At Last', performance_notes: 'Etta James classic with full band' },
  { contestant_name: 'Sara Ahmed', episode_no: 7, performance_order: 2, song_title: 'Feeling Good', performance_notes: 'Nina Simone cover with jazz arrangement' },
  
  // Muhammad Usman performances
  { contestant_name: 'Muhammad Usman', episode_no: 1, performance_order: 8, song_title: 'Bohemian Rhapsody', performance_notes: 'Queen classic with rock arrangement' },
  { contestant_name: 'Muhammad Usman', episode_no: 2, performance_order: 7, song_title: 'Highway to Hell', performance_notes: 'AC/DC cover with electric guitar' },
  { contestant_name: 'Muhammad Usman', episode_no: 4, performance_order: 8, song_title: 'Sweet Child O Mine', performance_notes: 'Guns N Roses with full rock band' },
  
  // Zainab Malik performances
  { contestant_name: 'Zainab Malik', episode_no: 6, performance_order: 2, song_title: 'Balochi Folk Song', performance_notes: 'Traditional Balochi song with dholak' },
  { contestant_name: 'Zainab Malik', episode_no: 7, performance_order: 1, song_title: 'Sindhi Kalaam', performance_notes: 'Sufi poetry with traditional instruments' },
  { contestant_name: 'Zainab Malik', episode_no: 8, performance_order: 3, song_title: 'Mast Qalandar', performance_notes: 'Sufi qawwali with harmonium and tabla' },
  
  // Ali Hassan performances
  { contestant_name: 'Ali Hassan', episode_no: 9, performance_order: 2, song_title: 'Dama Dam Mast Qalandar', performance_notes: 'Classic Sufi qawwali with traditional instruments' },
  { contestant_name: 'Ali Hassan', episode_no: 10, performance_order: 4, song_title: 'Allah Hoo', performance_notes: 'Sufi devotional song with harmonium' },
  { contestant_name: 'Ali Hassan', episode_no: 11, performance_order: 1, song_title: 'Kun Faya Kun', performance_notes: 'Rockstar movie qawwali with modern arrangement' },
  
  // Nida Khan performances
  { contestant_name: 'Nida Khan', episode_no: 10, performance_order: 1, song_title: 'Piya Basanti', performance_notes: 'Classical raga with high-pitched vocals' },
  { contestant_name: 'Nida Khan', episode_no: 11, performance_order: 3, song_title: 'Ae Mere Humsafar', performance_notes: 'Classical Bollywood song with tabla' },
  { contestant_name: 'Nida Khan', episode_no: 12, performance_order: 2, song_title: 'Thumri in Raag Yaman', performance_notes: 'Classical thumri with piano accompaniment' },
  
  // Omar Sheikh performances
  { contestant_name: 'Omar Sheikh', episode_no: 1, performance_order: 4, song_title: 'A Change Is Gonna Come', performance_notes: 'Sam Cooke R&B classic with soulful delivery' },
  { contestant_name: 'Omar Sheikh', episode_no: 3, performance_order: 4, song_title: 'Stand By Me', performance_notes: 'Ben E. King cover with piano and strings' },
  { contestant_name: 'Omar Sheikh', episode_no: 7, performance_order: 3, song_title: 'What A Wonderful World', performance_notes: 'Louis Armstrong jazz standard with piano' },
  
  // Eliminated contestants performances
  { contestant_name: 'Saima Bibi', episode_no: 1, performance_order: 1, song_title: 'Classical Raag', performance_notes: 'Traditional classical performance' },
  { contestant_name: 'Rashid Ahmed', episode_no: 2, performance_order: 1, song_title: 'Pashto Folk Song', performance_notes: 'Traditional Pashto song' },
  { contestant_name: 'Mehwish Khan', episode_no: 3, performance_order: 5, song_title: 'Tum Hi Aana', performance_notes: 'Bollywood song with stage fright issues' },
  { contestant_name: 'Bilal Qureshi', episode_no: 4, performance_order: 3, song_title: 'Enter Sandman', performance_notes: 'Metallica cover with rock band' },
  { contestant_name: 'Amina Shah', episode_no: 5, performance_order: 2, song_title: 'Luka Chuppi', performance_notes: 'Young talent with classical song' },
];

export const sampleContestantScores = [
  // Ayesha Khan scores
  { contestant_name: 'Ayesha Khan', episode_no: 1, judge_name: 'Fawad Khan', score: 8.5, remarks: 'Beautiful classical rendition. Excellent control.' },
  { contestant_name: 'Ayesha Khan', episode_no: 1, judge_name: 'Zeb Bangash', score: 8.0, remarks: 'Good technique, needs more emotion.' },
  { contestant_name: 'Ayesha Khan', episode_no: 1, judge_name: 'Rahat Fateh Ali Khan', score: 9.0, remarks: 'Outstanding performance. Perfect pitch.' },
  { contestant_name: 'Ayesha Khan', episode_no: 1, judge_name: 'Bilal Maqsood', score: 8.5, remarks: 'Great classical foundation and vocal control.' },
  
  // Hassan Ali scores
  { contestant_name: 'Hassan Ali', episode_no: 1, judge_name: 'Fawad Khan', score: 7.5, remarks: 'Good energy, guitar skills are impressive.' },
  { contestant_name: 'Hassan Ali', episode_no: 1, judge_name: 'Zeb Bangash', score: 8.5, remarks: 'Great stage presence and modern style.' },
  { contestant_name: 'Hassan Ali', episode_no: 1, judge_name: 'Rahat Fateh Ali Khan', score: 7.0, remarks: 'Needs to work on vocal clarity.' },
  { contestant_name: 'Hassan Ali', episode_no: 1, judge_name: 'Bilal Maqsood', score: 8.0, remarks: 'Good musical arrangement and performance.' },
  
  // Fatima Sheikh scores
  { contestant_name: 'Fatima Sheikh', episode_no: 2, judge_name: 'Fawad Khan', score: 8.0, remarks: 'Young talent with great potential.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 2, judge_name: 'Zeb Bangash', score: 8.5, remarks: 'Powerful voice for her age.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 2, judge_name: 'Rahat Fateh Ali Khan', score: 8.5, remarks: 'Excellent song choice and delivery.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 2, judge_name: 'Bilal Maqsood', score: 8.2, remarks: 'Good interpretation and emotional connection.' },
  
  // Ahmed Raza scores
  { contestant_name: 'Ahmed Raza', episode_no: 2, judge_name: 'Fawad Khan', score: 7.0, remarks: 'Unique cultural representation.' },
  { contestant_name: 'Ahmed Raza', episode_no: 2, judge_name: 'Zeb Bangash', score: 7.5, remarks: 'Good folk music performance.' },
  { contestant_name: 'Ahmed Raza', episode_no: 2, judge_name: 'Rahat Fateh Ali Khan', score: 8.0, remarks: 'Authentic and heartfelt.' },
  { contestant_name: 'Ahmed Raza', episode_no: 2, judge_name: 'Bilal Maqsood', score: 7.8, remarks: 'Traditional style with good execution.' },
  
  // Sara Ahmed scores
  { contestant_name: 'Sara Ahmed', episode_no: 3, judge_name: 'Fawad Khan', score: 9.0, remarks: 'Exceptional jazz performance.' },
  { contestant_name: 'Sara Ahmed', episode_no: 3, judge_name: 'Zeb Bangash', score: 8.5, remarks: 'Unique style and great control.' },
  { contestant_name: 'Sara Ahmed', episode_no: 3, judge_name: 'Rahat Fateh Ali Khan', score: 9.5, remarks: 'Golden mic worthy performance!' },
  { contestant_name: 'Sara Ahmed', episode_no: 3, judge_name: 'Bilal Maqsood', score: 9.2, remarks: 'Outstanding musicality and stage presence.' },
  
  // Eliminated contestants scores
  { contestant_name: 'Saima Bibi', episode_no: 1, judge_name: 'Fawad Khan', score: 6.0, remarks: 'Good classical voice but struggled with modern songs.' },
  { contestant_name: 'Saima Bibi', episode_no: 1, judge_name: 'Zeb Bangash', score: 5.5, remarks: 'Needs to work on contemporary style.' },
  { contestant_name: 'Saima Bibi', episode_no: 1, judge_name: 'Rahat Fateh Ali Khan', score: 7.0, remarks: 'Classical foundation is strong.' },
  { contestant_name: 'Saima Bibi', episode_no: 1, judge_name: 'Bilal Maqsood', score: 5.8, remarks: 'Limited range in modern music.' },
  
  { contestant_name: 'Rashid Ahmed', episode_no: 2, judge_name: 'Fawad Khan', score: 6.5, remarks: 'Great folk music but language barrier was an issue.' },
  { contestant_name: 'Rashid Ahmed', episode_no: 2, judge_name: 'Zeb Bangash', score: 6.0, remarks: 'Authentic Pashto performance.' },
  { contestant_name: 'Rashid Ahmed', episode_no: 2, judge_name: 'Rahat Fateh Ali Khan', score: 6.8, remarks: 'Traditional style is commendable.' },
  { contestant_name: 'Rashid Ahmed', episode_no: 2, judge_name: 'Bilal Maqsood', score: 5.5, remarks: 'Needs to expand repertoire.' },
  
  { contestant_name: 'Mehwish Khan', episode_no: 3, judge_name: 'Fawad Khan', score: 4.5, remarks: 'Stage fright affected performance badly.' },
  { contestant_name: 'Mehwish Khan', episode_no: 3, judge_name: 'Zeb Bangash', score: 5.0, remarks: 'Good voice but confidence issues.' },
  { contestant_name: 'Mehwish Khan', episode_no: 3, judge_name: 'Rahat Fateh Ali Khan', score: 4.8, remarks: 'Potential is there but needs work.' },
  { contestant_name: 'Mehwish Khan', episode_no: 3, judge_name: 'Bilal Maqsood', score: 4.2, remarks: 'Performance was disappointing.' },
  
  { contestant_name: 'Bilal Qureshi', episode_no: 4, judge_name: 'Fawad Khan', score: 7.5, remarks: 'Good rock performance but not consistent.' },
  { contestant_name: 'Bilal Qureshi', episode_no: 4, judge_name: 'Zeb Bangash', score: 7.0, remarks: 'Had potential but eliminated in semis.' },
  { contestant_name: 'Bilal Qureshi', episode_no: 4, judge_name: 'Rahat Fateh Ali Khan', score: 6.5, remarks: 'Rock style is not my preference.' },
  { contestant_name: 'Bilal Qureshi', episode_no: 4, judge_name: 'Bilal Maqsood', score: 8.0, remarks: 'Good energy and stage presence.' },
  
  { contestant_name: 'Amina Shah', episode_no: 5, judge_name: 'Fawad Khan', score: 6.0, remarks: 'Young talent but lacks experience.' },
  { contestant_name: 'Amina Shah', episode_no: 5, judge_name: 'Zeb Bangash', score: 6.5, remarks: 'Good voice for her age.' },
  { contestant_name: 'Amina Shah', episode_no: 5, judge_name: 'Rahat Fateh Ali Khan', score: 5.8, remarks: 'Needs more training and practice.' },
  { contestant_name: 'Amina Shah', episode_no: 5, judge_name: 'Bilal Maqsood', score: 6.2, remarks: 'Future potential but not ready yet.' },
  
  // Additional scores for multiple episodes - Ayesha Khan
  { contestant_name: 'Ayesha Khan', episode_no: 3, judge_name: 'Fawad Khan', score: 8.8, remarks: 'Excellent piano workshop performance.' },
  { contestant_name: 'Ayesha Khan', episode_no: 3, judge_name: 'Zeb Bangash', score: 8.5, remarks: 'Great adaptation to piano accompaniment.' },
  { contestant_name: 'Ayesha Khan', episode_no: 3, judge_name: 'Rahat Fateh Ali Khan', score: 9.2, remarks: 'Perfect classical technique with piano.' },
  { contestant_name: 'Ayesha Khan', episode_no: 3, judge_name: 'Bilal Maqsood', score: 8.7, remarks: 'Beautiful rendition of classic song.' },
  
  { contestant_name: 'Ayesha Khan', episode_no: 4, judge_name: 'Fawad Khan', score: 9.0, remarks: 'Stunning gala performance with orchestra.' },
  { contestant_name: 'Ayesha Khan', episode_no: 4, judge_name: 'Zeb Bangash', score: 8.8, remarks: 'Emotional delivery with full arrangement.' },
  { contestant_name: 'Ayesha Khan', episode_no: 4, judge_name: 'Rahat Fateh Ali Khan', score: 9.5, remarks: 'Golden mic worthy performance!' },
  { contestant_name: 'Ayesha Khan', episode_no: 4, judge_name: 'Bilal Maqsood', score: 9.1, remarks: 'Outstanding musicality and control.' },
  
  // Additional scores for Hassan Ali
  { contestant_name: 'Hassan Ali', episode_no: 2, judge_name: 'Fawad Khan', score: 8.0, remarks: 'Good modern song choice and execution.' },
  { contestant_name: 'Hassan Ali', episode_no: 2, judge_name: 'Zeb Bangash', score: 8.2, remarks: 'Great guitar work and vocal delivery.' },
  { contestant_name: 'Hassan Ali', episode_no: 2, judge_name: 'Rahat Fateh Ali Khan', score: 7.8, remarks: 'Good performance but needs more emotion.' },
  { contestant_name: 'Hassan Ali', episode_no: 2, judge_name: 'Bilal Maqsood', score: 8.5, remarks: 'Excellent musical arrangement.' },
  
  { contestant_name: 'Hassan Ali', episode_no: 4, judge_name: 'Fawad Khan', score: 8.5, remarks: 'Great international song choice.' },
  { contestant_name: 'Hassan Ali', episode_no: 4, judge_name: 'Zeb Bangash', score: 8.7, remarks: 'Good adaptation of English song.' },
  { contestant_name: 'Hassan Ali', episode_no: 4, judge_name: 'Rahat Fateh Ali Khan', score: 7.5, remarks: 'Prefer more traditional songs.' },
  { contestant_name: 'Hassan Ali', episode_no: 4, judge_name: 'Bilal Maqsood', score: 8.8, remarks: 'Excellent guitar and harmonica work.' },
  
  // Additional scores for Fatima Sheikh
  { contestant_name: 'Fatima Sheikh', episode_no: 3, judge_name: 'Fawad Khan', score: 8.3, remarks: 'Good emotional delivery in piano workshop.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 3, judge_name: 'Zeb Bangash', score: 8.6, remarks: 'Great adaptation to piano accompaniment.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 3, judge_name: 'Rahat Fateh Ali Khan', score: 8.4, remarks: 'Good song choice and execution.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 3, judge_name: 'Bilal Maqsood', score: 8.5, remarks: 'Excellent emotional connection.' },
  
  { contestant_name: 'Fatima Sheikh', episode_no: 6, judge_name: 'Fawad Khan', score: 8.7, remarks: 'Great performance with piano.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 6, judge_name: 'Zeb Bangash', score: 8.9, remarks: 'Excellent song choice and delivery.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 6, judge_name: 'Rahat Fateh Ali Khan', score: 8.6, remarks: 'Good technique and emotion.' },
  { contestant_name: 'Fatima Sheikh', episode_no: 6, judge_name: 'Bilal Maqsood', score: 8.8, remarks: 'Outstanding performance.' },
  
  // Additional scores for Sara Ahmed
  { contestant_name: 'Sara Ahmed', episode_no: 4, judge_name: 'Fawad Khan', score: 9.2, remarks: 'Exceptional jazz performance with full band.' },
  { contestant_name: 'Sara Ahmed', episode_no: 4, judge_name: 'Zeb Bangash', score: 9.0, remarks: 'Outstanding musicality and stage presence.' },
  { contestant_name: 'Sara Ahmed', episode_no: 4, judge_name: 'Rahat Fateh Ali Khan', score: 8.8, remarks: 'Great jazz interpretation.' },
  { contestant_name: 'Sara Ahmed', episode_no: 4, judge_name: 'Bilal Maqsood', score: 9.3, remarks: 'Golden mic worthy performance!' },
  
  { contestant_name: 'Sara Ahmed', episode_no: 7, judge_name: 'Fawad Khan', score: 8.9, remarks: 'Excellent jazz standard performance.' },
  { contestant_name: 'Sara Ahmed', episode_no: 7, judge_name: 'Zeb Bangash', score: 9.1, remarks: 'Great jazz arrangement and delivery.' },
  { contestant_name: 'Sara Ahmed', episode_no: 7, judge_name: 'Rahat Fateh Ali Khan', score: 8.7, remarks: 'Good jazz technique.' },
  { contestant_name: 'Sara Ahmed', episode_no: 7, judge_name: 'Bilal Maqsood', score: 9.0, remarks: 'Outstanding musical interpretation.' },
  
  // Additional scores for Muhammad Usman
  { contestant_name: 'Muhammad Usman', episode_no: 2, judge_name: 'Fawad Khan', score: 8.0, remarks: 'Good rock performance with energy.' },
  { contestant_name: 'Muhammad Usman', episode_no: 2, judge_name: 'Zeb Bangash', score: 7.8, remarks: 'Great stage presence and guitar work.' },
  { contestant_name: 'Muhammad Usman', episode_no: 2, judge_name: 'Rahat Fateh Ali Khan', score: 7.0, remarks: 'Rock is not my preference but good energy.' },
  { contestant_name: 'Muhammad Usman', episode_no: 2, judge_name: 'Bilal Maqsood', score: 8.5, remarks: 'Excellent rock performance.' },
  
  { contestant_name: 'Muhammad Usman', episode_no: 4, judge_name: 'Fawad Khan', score: 8.3, remarks: 'Great rock performance with full band.' },
  { contestant_name: 'Muhammad Usman', episode_no: 4, judge_name: 'Zeb Bangash', score: 8.1, remarks: 'Good energy and stage presence.' },
  { contestant_name: 'Muhammad Usman', episode_no: 4, judge_name: 'Rahat Fateh Ali Khan', score: 7.2, remarks: 'Rock style but good execution.' },
  { contestant_name: 'Muhammad Usman', episode_no: 4, judge_name: 'Bilal Maqsood', score: 8.7, remarks: 'Outstanding rock performance.' },
];
